name: Build C libs

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --build-arg BUILD_TYPE=${{ github.event.inputs.build_type }} -t clibs .

      - name: Run Docker container and build libs
        run: |
          mkdir build
          docker run --rm -v $PWD/build:/build clibs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clibs
          path: build
          retention-days: 30
